#!/usr/bin/bash

git submodule update --init

script_path=$(readlink -f $0)
base_dir=$(dirname $script_path)

cd "$base_dir"

mkdir -p work out/repo

sudo bash -c "archmk-pkgs && \
              archmk-root &&
              archmk-ostree"
